/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"

#ifndef _Included_opengl_panjq_com_opengl_demo_RendererJNI
#define _Included_opengl_panjq_com_opengl_demo_RendererJNI
#ifdef __cplusplus
#endif
/*
 * Class:     opengl_panjq_com_opengl_demo_RendererJNI
 * Method:    glesInit
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_milk_demo4_RendererJNI_glesInit
        (JNIEnv *, jobject);

/*
 * Class:     opengl_panjq_com_opengl_demo_RendererJNI
 * Method:    glesRender
 * Signature: ()V
 */
extern "C" JNIEXPORT void JNICALL Java_com_milk_demo4_RendererJNI_glesRender
        (JNIEnv *, jobject);

/*
 * Class:     opengl_panjq_com_opengl_demo_RendererJNI
 * Method:    glesResize
 * Signature: (II)V
 */
extern "C" JNIEXPORT void JNICALL Java_com_milk_demo4_RendererJNI_glesResize
        (JNIEnv *, jobject, jint, jint);


extern "C" JNIEXPORT void JNICALL Java_com_milk_demo4_RendererJNI_readShaderFile
        (JNIEnv *env, jobject self, jobject assetManager);

#ifdef __cplusplus
#endif
#endif


